/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.placecube.nhs.userprivacy.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import com.placecube.nhs.userprivacy.model.UserPrivacy;
import com.placecube.nhs.userprivacy.model.UserPrivacyModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the UserPrivacy service. Represents a row in the &quot;NHS_Privacy_UserPrivacy&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>UserPrivacyModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UserPrivacyImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserPrivacyImpl
 * @generated
 */
@ProviderType
public class UserPrivacyModelImpl
	extends BaseModelImpl<UserPrivacy> implements UserPrivacyModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a user privacy model instance should use the <code>UserPrivacy</code> interface instead.
	 */
	public static final String TABLE_NAME = "NHS_Privacy_UserPrivacy";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"userPrivacyId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"fieldId", Types.VARCHAR}, {"roleIds", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("userPrivacyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("fieldId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("roleIds", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table NHS_Privacy_UserPrivacy (uuid_ VARCHAR(75) null,userPrivacyId LONG not null primary key,companyId LONG,userId LONG,fieldId VARCHAR(500) null,roleIds VARCHAR(500) null,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table NHS_Privacy_UserPrivacy";

	public static final String ORDER_BY_JPQL =
		" ORDER BY userPrivacy.userPrivacyId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY NHS_Privacy_UserPrivacy.userPrivacyId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long UUID_COLUMN_BITMASK = 2L;

	public static final long USERPRIVACYID_COLUMN_BITMASK = 4L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public UserPrivacyModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _userPrivacyId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setUserPrivacyId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _userPrivacyId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return UserPrivacy.class;
	}

	@Override
	public String getModelClassName() {
		return UserPrivacy.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<UserPrivacy, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<UserPrivacy, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<UserPrivacy, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((UserPrivacy)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<UserPrivacy, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<UserPrivacy, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(UserPrivacy)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<UserPrivacy, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<UserPrivacy, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, UserPrivacy>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			UserPrivacy.class.getClassLoader(), UserPrivacy.class,
			ModelWrapper.class);

		try {
			Constructor<UserPrivacy> constructor =
				(Constructor<UserPrivacy>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<UserPrivacy, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<UserPrivacy, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<UserPrivacy, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<UserPrivacy, Object>>();
		Map<String, BiConsumer<UserPrivacy, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<UserPrivacy, ?>>();

		attributeGetterFunctions.put("uuid", UserPrivacy::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<UserPrivacy, String>)UserPrivacy::setUuid);
		attributeGetterFunctions.put(
			"userPrivacyId", UserPrivacy::getUserPrivacyId);
		attributeSetterBiConsumers.put(
			"userPrivacyId",
			(BiConsumer<UserPrivacy, Long>)UserPrivacy::setUserPrivacyId);
		attributeGetterFunctions.put("companyId", UserPrivacy::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<UserPrivacy, Long>)UserPrivacy::setCompanyId);
		attributeGetterFunctions.put("userId", UserPrivacy::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<UserPrivacy, Long>)UserPrivacy::setUserId);
		attributeGetterFunctions.put("fieldId", UserPrivacy::getFieldId);
		attributeSetterBiConsumers.put(
			"fieldId",
			(BiConsumer<UserPrivacy, String>)UserPrivacy::setFieldId);
		attributeGetterFunctions.put("roleIds", UserPrivacy::getRoleIds);
		attributeSetterBiConsumers.put(
			"roleIds",
			(BiConsumer<UserPrivacy, String>)UserPrivacy::setRoleIds);
		attributeGetterFunctions.put("createDate", UserPrivacy::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<UserPrivacy, Date>)UserPrivacy::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", UserPrivacy::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<UserPrivacy, Date>)UserPrivacy::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getUserPrivacyId() {
		return _userPrivacyId;
	}

	@Override
	public void setUserPrivacyId(long userPrivacyId) {
		_userPrivacyId = userPrivacyId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getFieldId() {
		if (_fieldId == null) {
			return "";
		}
		else {
			return _fieldId;
		}
	}

	@Override
	public void setFieldId(String fieldId) {
		_fieldId = fieldId;
	}

	@Override
	public String getRoleIds() {
		if (_roleIds == null) {
			return "";
		}
		else {
			return _roleIds;
		}
	}

	@Override
	public void setRoleIds(String roleIds) {
		_roleIds = roleIds;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(UserPrivacy.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), UserPrivacy.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public UserPrivacy toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = _escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		UserPrivacyImpl userPrivacyImpl = new UserPrivacyImpl();

		userPrivacyImpl.setUuid(getUuid());
		userPrivacyImpl.setUserPrivacyId(getUserPrivacyId());
		userPrivacyImpl.setCompanyId(getCompanyId());
		userPrivacyImpl.setUserId(getUserId());
		userPrivacyImpl.setFieldId(getFieldId());
		userPrivacyImpl.setRoleIds(getRoleIds());
		userPrivacyImpl.setCreateDate(getCreateDate());
		userPrivacyImpl.setModifiedDate(getModifiedDate());

		userPrivacyImpl.resetOriginalValues();

		return userPrivacyImpl;
	}

	@Override
	public int compareTo(UserPrivacy userPrivacy) {
		long primaryKey = userPrivacy.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof UserPrivacy)) {
			return false;
		}

		UserPrivacy userPrivacy = (UserPrivacy)obj;

		long primaryKey = userPrivacy.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		UserPrivacyModelImpl userPrivacyModelImpl = this;

		userPrivacyModelImpl._originalUuid = userPrivacyModelImpl._uuid;

		userPrivacyModelImpl._originalCompanyId =
			userPrivacyModelImpl._companyId;

		userPrivacyModelImpl._setOriginalCompanyId = false;

		userPrivacyModelImpl._setModifiedDate = false;

		userPrivacyModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<UserPrivacy> toCacheModel() {
		UserPrivacyCacheModel userPrivacyCacheModel =
			new UserPrivacyCacheModel();

		userPrivacyCacheModel.uuid = getUuid();

		String uuid = userPrivacyCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			userPrivacyCacheModel.uuid = null;
		}

		userPrivacyCacheModel.userPrivacyId = getUserPrivacyId();

		userPrivacyCacheModel.companyId = getCompanyId();

		userPrivacyCacheModel.userId = getUserId();

		userPrivacyCacheModel.fieldId = getFieldId();

		String fieldId = userPrivacyCacheModel.fieldId;

		if ((fieldId != null) && (fieldId.length() == 0)) {
			userPrivacyCacheModel.fieldId = null;
		}

		userPrivacyCacheModel.roleIds = getRoleIds();

		String roleIds = userPrivacyCacheModel.roleIds;

		if ((roleIds != null) && (roleIds.length() == 0)) {
			userPrivacyCacheModel.roleIds = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			userPrivacyCacheModel.createDate = createDate.getTime();
		}
		else {
			userPrivacyCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			userPrivacyCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			userPrivacyCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return userPrivacyCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<UserPrivacy, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<UserPrivacy, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<UserPrivacy, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((UserPrivacy)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<UserPrivacy, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<UserPrivacy, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<UserPrivacy, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((UserPrivacy)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final Function<InvocationHandler, UserPrivacy>
		_escapedModelProxyProviderFunction = _getProxyProviderFunction();
	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _userPrivacyId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _fieldId;
	private String _roleIds;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _columnBitmask;
	private UserPrivacy _escapedModel;

}