/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.placecube.nhs.notification.model.impl;

import com.placecube.nhs.notification.model.UserNotificationPreference;
import com.placecube.nhs.notification.service.UserNotificationPreferenceLocalServiceUtil;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The extended model base implementation for the UserNotificationPreference service. Represents a row in the &quot;NHS_Notification_UserNotificationPreference&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UserNotificationPreferenceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserNotificationPreferenceImpl
 * @see UserNotificationPreference
 * @generated
 */
@ProviderType
public abstract class UserNotificationPreferenceBaseImpl
	extends UserNotificationPreferenceModelImpl
	implements UserNotificationPreference {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a user notification preference model instance should use the <code>UserNotificationPreference</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			UserNotificationPreferenceLocalServiceUtil.
				addUserNotificationPreference(this);
		}
		else {
			UserNotificationPreferenceLocalServiceUtil.
				updateUserNotificationPreference(this);
		}
	}

}