/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.placecube.nhs.userprivacy.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import com.placecube.nhs.userprivacy.service.persistence.UserPrivacyPK;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the UserPrivacy service. Represents a row in the &quot;NHS_Privacy_UserPrivacy&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.placecube.nhs.userprivacy.model.impl.UserPrivacyModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.placecube.nhs.userprivacy.model.impl.UserPrivacyImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserPrivacy
 * @generated
 */
@ProviderType
public interface UserPrivacyModel
	extends BaseModel<UserPrivacy>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user privacy model instance should use the {@link UserPrivacy} interface instead.
	 */

	/**
	 * Returns the primary key of this user privacy.
	 *
	 * @return the primary key of this user privacy
	 */
	public UserPrivacyPK getPrimaryKey();

	/**
	 * Sets the primary key of this user privacy.
	 *
	 * @param primaryKey the primary key of this user privacy
	 */
	public void setPrimaryKey(UserPrivacyPK primaryKey);

	/**
	 * Returns the uuid of this user privacy.
	 *
	 * @return the uuid of this user privacy
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this user privacy.
	 *
	 * @param uuid the uuid of this user privacy
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the user ID of this user privacy.
	 *
	 * @return the user ID of this user privacy
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user privacy.
	 *
	 * @param userId the user ID of this user privacy
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user privacy.
	 *
	 * @return the user uuid of this user privacy
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this user privacy.
	 *
	 * @param userUuid the user uuid of this user privacy
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the field ID of this user privacy.
	 *
	 * @return the field ID of this user privacy
	 */
	@AutoEscape
	public String getFieldId();

	/**
	 * Sets the field ID of this user privacy.
	 *
	 * @param fieldId the field ID of this user privacy
	 */
	public void setFieldId(String fieldId);

	/**
	 * Returns the company ID of this user privacy.
	 *
	 * @return the company ID of this user privacy
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this user privacy.
	 *
	 * @param companyId the company ID of this user privacy
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the role IDs of this user privacy.
	 *
	 * @return the role IDs of this user privacy
	 */
	@AutoEscape
	public String getRoleIds();

	/**
	 * Sets the role IDs of this user privacy.
	 *
	 * @param roleIds the role IDs of this user privacy
	 */
	public void setRoleIds(String roleIds);

	/**
	 * Returns the create date of this user privacy.
	 *
	 * @return the create date of this user privacy
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this user privacy.
	 *
	 * @param createDate the create date of this user privacy
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this user privacy.
	 *
	 * @return the modified date of this user privacy
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this user privacy.
	 *
	 * @param modifiedDate the modified date of this user privacy
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

}